name: cmpy
channels:
  - conda-forge
dependencies:
  - python=2.7
  - dit==1.2.3
  #- ipython==5.3.0
  - openmdao # <2
  - networkx
  - cython
  - scipy
  - matplotlib>=2.1,<3
  - sympy
  - pygraphviz
