name: cmpy
channels:
  - conda-forge
dependencies:
  - python=2.7
  - dit==1.2.3
  - ipython==5.3.0
  - networkx==1.11
  - cython
  - scipy
  - matplotlib>=2.1,<3
  - sympy
  - pygraphviz
  - plotly
  - qutip
  - pip
  - pip:
    - openmdao<2
    - yapf
